/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MovieTicketing;

/**
 *
 This project is coded by Md shahajalal.
 * Bsc in CSE NWU,Khulna.
 */
public class MovieTicket extends javax.swing.JFrame {

    /**
     * Creates new form MovieTicket
     */
    public MovieTicket() {
        setTitle("Movie Ticket System");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxt1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTxt2 = new javax.swing.JTextField();
        jTxt3 = new javax.swing.JTextField();
        jTxt4 = new javax.swing.JTextField();
        jTxt5 = new javax.swing.JTextField();
        jRadio1 = new javax.swing.JRadioButton();
        jRadio2 = new javax.swing.JRadioButton();
        jRadio3 = new javax.swing.JRadioButton();
        jRadio4 = new javax.swing.JRadioButton();
        jRadio5 = new javax.swing.JRadioButton();
        jRadio6 = new javax.swing.JRadioButton();
        jRadio7 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jTxt6 = new javax.swing.JTextField();
        jTxt7 = new javax.swing.JTextField();
        jTxt8 = new javax.swing.JTextField();
        jTxt9 = new javax.swing.JTextField();
        jTxt10 = new javax.swing.JTextField();
        jTxt11 = new javax.swing.JTextField();
        jBtm1 = new javax.swing.JButton();
        jBtm2 = new javax.swing.JButton();
        jBtm3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTxt12 = new javax.swing.JTextField();
        jTxt13 = new javax.swing.JTextField();
        jTxt14 = new javax.swing.JTextField();
        jTxt15 = new javax.swing.JTextField();
        jTxt16 = new javax.swing.JTextField();
        jTxt17 = new javax.swing.JTextField();
        jTxt18 = new javax.swing.JTextField();
        jTxt19 = new javax.swing.JTextField();
        jTxt20 = new javax.swing.JTextField();
        jTxt21 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTxt1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTxt1.setText("MOVIE TICKETING SYSTEM");
        jTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jTxt2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt2.setText("Class");

        jTxt3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt3.setText("Type");

        jTxt4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt4.setText("Child");

        jTxt5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt5.setText("Adult");

        jRadio1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadio1.setText("First class");

        jRadio2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadio2.setText("Second class");

        jRadio3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadio3.setText("Third class");

        jRadio4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadio4.setText("single");

        jRadio5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadio5.setText("Double");

        jRadio6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadio6.setText("yes");

        jRadio7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadio7.setText("yes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadio1)
                    .addComponent(jRadio2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadio4)
                    .addComponent(jRadio5))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadio6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadio7)
                        .addGap(16, 16, 16))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadio3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadio6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadio5)
                                    .addComponent(jRadio2)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadio4)
                                .addComponent(jRadio1))
                            .addComponent(jRadio7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadio3)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jTxt6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt6.setText("Original rate");

        jTxt7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt7.setText("Tax");

        jTxt8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt8.setText("Total rate");

        jTxt9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jTxt10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jTxt11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jBtm1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtm1.setText("Total");
        jBtm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtm1ActionPerformed(evt);
            }
        });

        jBtm2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtm2.setText("Reset");
        jBtm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtm2ActionPerformed(evt);
            }
        });

        jBtm3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtm3.setText("Exit");
        jBtm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtm3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtm1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxt9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBtm2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtm3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxt10)
                            .addComponent(jTxt11))))
                .addGap(3, 3, 3))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTxt10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtm2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jBtm3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jTxt12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt12.setText("Class");

        jTxt13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt13.setText("Type");

        jTxt14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt14.setText("Adult");

        jTxt15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt15.setText("Child");

        jTxt16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt16.setText("Total");

        jTxt17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jTxt17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt17ActionPerformed(evt);
            }
        });

        jTxt18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jTxt19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jTxt20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jTxt21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxt21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTxt12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxt17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTxt13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jTxt18, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTxt14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxt19, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTxt15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxt20, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTxt16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxt21, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt1ActionPerformed

    private void jBtm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtm3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtm3ActionPerformed

    private void jBtm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtm2ActionPerformed
        jTxt9.setText(null);
        jTxt10.setText(null);
        jTxt11.setText(null);
        jTxt17.setText(null);
        jTxt18.setText(null);
        jTxt19.setText(null);
        jTxt20.setText(null);
        jTxt21.setText(null);
    }//GEN-LAST:event_jBtm2ActionPerformed

    private void jTxt17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt17ActionPerformed

    private void jBtm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtm1ActionPerformed
        double tax=17;
        double ftotal=50;
        double stotal=100;
        double ttotal=150;
        //for first class
        if((jRadio1.isSelected())&&(jRadio4.isSelected())&&(jRadio7.isSelected()))
        {
            jTxt10.setText(String.valueOf(tax));
            jTxt9.setText(String.valueOf(ftotal));
            jTxt11.setText(String.valueOf(tax+ftotal));
            jTxt17.setText("First");
            jTxt18.setText("Single");
            jTxt19.setText("One");
            jTxt20.setText("NO");
            jTxt21.setText(String.valueOf(tax+ftotal));
        }
        else if((jRadio1.isSelected())&&(jRadio5.isSelected())&&(jRadio7.isSelected()))
        {
            jTxt10.setText(String.valueOf(tax));
            jTxt9.setText(String.valueOf(ftotal*2));
            jTxt11.setText(String.valueOf(tax+ftotal*2));
            jTxt17.setText("First");
            jTxt18.setText("Double");
            jTxt19.setText("Two");
            jTxt20.setText("NO");
            jTxt21.setText(String.valueOf(tax+ftotal*2));
        }
        else if((jRadio1.isSelected())&&(jRadio4.isSelected())&&(jRadio6.isSelected()))
        {
            jTxt10.setText("0");
            jTxt9.setText(String.valueOf(ftotal));
            jTxt11.setText(String.valueOf(ftotal));
            jTxt17.setText("First");
            jTxt18.setText("Single");
            jTxt19.setText("NO");
            jTxt20.setText("ONE");
            jTxt21.setText(String.valueOf(ftotal));
        }
        else if((jRadio1.isSelected())&&(jRadio5.isSelected())&&(jRadio6.isSelected()))
        {
            jTxt10.setText("0");
            jTxt9.setText(String.valueOf(ftotal*2));
            jTxt11.setText(String.valueOf(ftotal*2));
            jTxt17.setText("First");
            jTxt18.setText("Double");
            jTxt19.setText("NO");
            jTxt20.setText("TWO");
            jTxt21.setText(String.valueOf(ftotal*2));
        }
        //For second class
        if((jRadio2.isSelected())&&(jRadio4.isSelected())&&(jRadio7.isSelected()))
        {
            jTxt10.setText(String.valueOf(tax));
            jTxt9.setText(String.valueOf(stotal));
            jTxt11.setText(String.valueOf(tax+stotal));
            jTxt17.setText("SECOND");
            jTxt18.setText("Single");
            jTxt19.setText("One");
            jTxt20.setText("NO");
            jTxt21.setText(String.valueOf(tax+stotal));
        }
        else if((jRadio2.isSelected())&&(jRadio5.isSelected())&&(jRadio7.isSelected()))
        {
            jTxt10.setText(String.valueOf(tax));
            jTxt9.setText(String.valueOf(stotal*2));
            jTxt11.setText(String.valueOf(tax+stotal*2));
            jTxt17.setText("SECOND");
            jTxt18.setText("Double");
            jTxt19.setText("Two");
            jTxt20.setText("NO");
            jTxt21.setText(String.valueOf(tax+stotal*2));
        }
        else if((jRadio2.isSelected())&&(jRadio4.isSelected())&&(jRadio6.isSelected()))
        {
            jTxt10.setText("0");
            jTxt9.setText(String.valueOf(stotal));
            jTxt11.setText(String.valueOf(stotal));
            jTxt17.setText("SECOND");
            jTxt18.setText("Single");
            jTxt19.setText("NO");
            jTxt20.setText("ONE");
            jTxt21.setText(String.valueOf(stotal));
        }
        else if((jRadio2.isSelected())&&(jRadio5.isSelected())&&(jRadio6.isSelected()))
        {
            jTxt10.setText("0");
            jTxt9.setText(String.valueOf(stotal*2));
            jTxt11.setText(String.valueOf(stotal*2));
            jTxt17.setText("SECOND");
            jTxt18.setText("Double");
            jTxt19.setText("NO");
            jTxt20.setText("TWO");
            jTxt21.setText(String.valueOf(stotal*2));
        }
        
        //For third class
        if((jRadio3.isSelected())&&(jRadio4.isSelected())&&(jRadio7.isSelected()))
        {
            jTxt10.setText(String.valueOf(tax));
            jTxt9.setText(String.valueOf(ttotal));
            jTxt11.setText(String.valueOf(tax+ttotal));
            jTxt17.setText("THIRD");
            jTxt18.setText("Single");
            jTxt19.setText("One");
            jTxt20.setText("NO");
            jTxt21.setText(String.valueOf(tax+ttotal));
        }
        else if((jRadio3.isSelected())&&(jRadio5.isSelected())&&(jRadio7.isSelected()))
        {
            jTxt10.setText(String.valueOf(tax));
            jTxt9.setText(String.valueOf(ttotal*2));
            jTxt11.setText(String.valueOf(tax+ttotal*2));
            jTxt17.setText("THIRD");
            jTxt18.setText("Double");
            jTxt19.setText("Two");
            jTxt20.setText("NO");
            jTxt21.setText(String.valueOf(tax+ttotal*2));
        }
        else if((jRadio3.isSelected())&&(jRadio4.isSelected())&&(jRadio6.isSelected()))
        {
            jTxt10.setText("0");
            jTxt9.setText(String.valueOf(ttotal));
            jTxt11.setText(String.valueOf(ttotal));
            jTxt17.setText("THIRD");
            jTxt18.setText("Single");
            jTxt19.setText("NO");
            jTxt20.setText("ONE");
            jTxt21.setText(String.valueOf(ttotal));
        }
        else if((jRadio3.isSelected())&&(jRadio5.isSelected())&&(jRadio6.isSelected()))
        {
            jTxt10.setText("0");
            jTxt9.setText(String.valueOf(ttotal*2));
            jTxt11.setText(String.valueOf(ttotal*2));
            jTxt17.setText("THIRD");
            jTxt18.setText("Double");
            jTxt19.setText("NO");
            jTxt20.setText("TWO");
            jTxt21.setText(String.valueOf(ttotal*2));
        }
        
        
    }//GEN-LAST:event_jBtm1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtm1;
    private javax.swing.JButton jBtm2;
    private javax.swing.JButton jBtm3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadio1;
    private javax.swing.JRadioButton jRadio2;
    private javax.swing.JRadioButton jRadio3;
    private javax.swing.JRadioButton jRadio4;
    private javax.swing.JRadioButton jRadio5;
    private javax.swing.JRadioButton jRadio6;
    private javax.swing.JRadioButton jRadio7;
    private javax.swing.JTextField jTxt1;
    private javax.swing.JTextField jTxt10;
    private javax.swing.JTextField jTxt11;
    private javax.swing.JTextField jTxt12;
    private javax.swing.JTextField jTxt13;
    private javax.swing.JTextField jTxt14;
    private javax.swing.JTextField jTxt15;
    private javax.swing.JTextField jTxt16;
    private javax.swing.JTextField jTxt17;
    private javax.swing.JTextField jTxt18;
    private javax.swing.JTextField jTxt19;
    private javax.swing.JTextField jTxt2;
    private javax.swing.JTextField jTxt20;
    private javax.swing.JTextField jTxt21;
    private javax.swing.JTextField jTxt3;
    private javax.swing.JTextField jTxt4;
    private javax.swing.JTextField jTxt5;
    private javax.swing.JTextField jTxt6;
    private javax.swing.JTextField jTxt7;
    private javax.swing.JTextField jTxt8;
    private javax.swing.JTextField jTxt9;
    // End of variables declaration//GEN-END:variables
}
